name: MeetsAudioRec
options:
  bundleIdPrefix: co.whatever
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.2"
    CURRENT_PROJECT_VERSION: "3"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  MeetsAudioRec:
    type: application
    platform: macOS
    sources:
      - MeetsAudioRec
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.whatever.MeetsAudioRec
        INFOPLIST_FILE: MeetsAudioRec/Info.plist
        CODE_SIGN_ENTITLEMENTS: MeetsAudioRec/MeetsAudioRec.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: G5G54TCH8W
    entitlements:
      path: MeetsAudioRec/MeetsAudioRec.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.device.audio-input: true
